drop policy "Allow anonymous read access to session_summaries" on "public"."session_summaries";

drop policy "Allow service role to insert/update session_summaries" on "public"."session_summaries";

drop policy "Allow service role to update session_summaries" on "public"."session_summaries";

revoke delete on table "public"."session_summaries" from "anon";

revoke insert on table "public"."session_summaries" from "anon";

revoke references on table "public"."session_summaries" from "anon";

revoke select on table "public"."session_summaries" from "anon";

revoke trigger on table "public"."session_summaries" from "anon";

revoke truncate on table "public"."session_summaries" from "anon";

revoke update on table "public"."session_summaries" from "anon";

revoke delete on table "public"."session_summaries" from "authenticated";

revoke insert on table "public"."session_summaries" from "authenticated";

revoke references on table "public"."session_summaries" from "authenticated";

revoke select on table "public"."session_summaries" from "authenticated";

revoke trigger on table "public"."session_summaries" from "authenticated";

revoke truncate on table "public"."session_summaries" from "authenticated";

revoke update on table "public"."session_summaries" from "authenticated";

revoke delete on table "public"."session_summaries" from "service_role";

revoke insert on table "public"."session_summaries" from "service_role";

revoke references on table "public"."session_summaries" from "service_role";

revoke select on table "public"."session_summaries" from "service_role";

revoke trigger on table "public"."session_summaries" from "service_role";

revoke truncate on table "public"."session_summaries" from "service_role";

revoke update on table "public"."session_summaries" from "service_role";

alter table "public"."session_summaries" drop constraint "session_summaries_session_id_fkey";

alter table "public"."session_summaries" drop constraint "session_summaries_session_id_key";

alter table "public"."session_summaries" drop constraint "session_summaries_pkey";

drop index if exists "public"."session_summaries_pkey";

drop index if exists "public"."session_summaries_session_id_key";

drop table "public"."session_summaries";

create table "public"."chapter_summaries" (
    "id" bigint generated by default as identity not null,
    "chapter_id" uuid not null default gen_random_uuid(),
    "session_id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "chapter_summary_text" text not null
);


alter table "public"."chapter_summaries" enable row level security;

create table "public"."conversation_summaries" (
    "id" bigint generated by default as identity not null,
    "chapter_id" uuid not null default gen_random_uuid(),
    "session_id" uuid not null default gen_random_uuid(),
    "chapter_section_id" uuid default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "summary_text" text not null
);


alter table "public"."conversation_summaries" enable row level security;

CREATE UNIQUE INDEX chapter_summaries_pkey ON public.chapter_summaries USING btree (id);

CREATE UNIQUE INDEX conversation_summaries_pkey ON public.conversation_summaries USING btree (id);

alter table "public"."chapter_summaries" add constraint "chapter_summaries_pkey" PRIMARY KEY using index "chapter_summaries_pkey";

alter table "public"."conversation_summaries" add constraint "conversation_summaries_pkey" PRIMARY KEY using index "conversation_summaries_pkey";

alter table "public"."chapter_summaries" add constraint "chapter_summaries_chapter_id_fkey" FOREIGN KEY (chapter_id) REFERENCES workbook_chapters(id) not valid;

alter table "public"."chapter_summaries" validate constraint "chapter_summaries_chapter_id_fkey";

alter table "public"."chapter_summaries" add constraint "chapter_summaries_session_id_fkey" FOREIGN KEY (session_id) REFERENCES user_sessions(id) not valid;

alter table "public"."chapter_summaries" validate constraint "chapter_summaries_session_id_fkey";

alter table "public"."conversation_summaries" add constraint "conversation_summaries_chapter_id_fkey" FOREIGN KEY (chapter_id) REFERENCES workbook_chapters(id) not valid;

alter table "public"."conversation_summaries" validate constraint "conversation_summaries_chapter_id_fkey";

alter table "public"."conversation_summaries" add constraint "conversation_summaries_chapter_section_id_fkey" FOREIGN KEY (chapter_section_id) REFERENCES workbook_sections(id) not valid;

alter table "public"."conversation_summaries" validate constraint "conversation_summaries_chapter_section_id_fkey";

alter table "public"."conversation_summaries" add constraint "conversation_summaries_session_id_fkey" FOREIGN KEY (session_id) REFERENCES user_sessions(id) not valid;

alter table "public"."conversation_summaries" validate constraint "conversation_summaries_session_id_fkey";

grant delete on table "public"."chapter_summaries" to "anon";

grant insert on table "public"."chapter_summaries" to "anon";

grant references on table "public"."chapter_summaries" to "anon";

grant select on table "public"."chapter_summaries" to "anon";

grant trigger on table "public"."chapter_summaries" to "anon";

grant truncate on table "public"."chapter_summaries" to "anon";

grant update on table "public"."chapter_summaries" to "anon";

grant delete on table "public"."chapter_summaries" to "authenticated";

grant insert on table "public"."chapter_summaries" to "authenticated";

grant references on table "public"."chapter_summaries" to "authenticated";

grant select on table "public"."chapter_summaries" to "authenticated";

grant trigger on table "public"."chapter_summaries" to "authenticated";

grant truncate on table "public"."chapter_summaries" to "authenticated";

grant update on table "public"."chapter_summaries" to "authenticated";

grant delete on table "public"."chapter_summaries" to "service_role";

grant insert on table "public"."chapter_summaries" to "service_role";

grant references on table "public"."chapter_summaries" to "service_role";

grant select on table "public"."chapter_summaries" to "service_role";

grant trigger on table "public"."chapter_summaries" to "service_role";

grant truncate on table "public"."chapter_summaries" to "service_role";

grant update on table "public"."chapter_summaries" to "service_role";

grant delete on table "public"."conversation_summaries" to "anon";

grant insert on table "public"."conversation_summaries" to "anon";

grant references on table "public"."conversation_summaries" to "anon";

grant select on table "public"."conversation_summaries" to "anon";

grant trigger on table "public"."conversation_summaries" to "anon";

grant truncate on table "public"."conversation_summaries" to "anon";

grant update on table "public"."conversation_summaries" to "anon";

grant delete on table "public"."conversation_summaries" to "authenticated";

grant insert on table "public"."conversation_summaries" to "authenticated";

grant references on table "public"."conversation_summaries" to "authenticated";

grant select on table "public"."conversation_summaries" to "authenticated";

grant trigger on table "public"."conversation_summaries" to "authenticated";

grant truncate on table "public"."conversation_summaries" to "authenticated";

grant update on table "public"."conversation_summaries" to "authenticated";

grant delete on table "public"."conversation_summaries" to "service_role";

grant insert on table "public"."conversation_summaries" to "service_role";

grant references on table "public"."conversation_summaries" to "service_role";

grant select on table "public"."conversation_summaries" to "service_role";

grant trigger on table "public"."conversation_summaries" to "service_role";

grant truncate on table "public"."conversation_summaries" to "service_role";

grant update on table "public"."conversation_summaries" to "service_role";

create policy "Allow anon users to read"
on "public"."chapter_summaries"
as permissive
for select
to anon
using (true);


create policy "Allow authenticated users to read"
on "public"."chapter_summaries"
as permissive
for select
to authenticated
using (true);


create policy "Allow anon users to read"
on "public"."conversation_summaries"
as permissive
for select
to anon
using (true);


create policy "Allow authenticated users to read"
on "public"."conversation_summaries"
as permissive
for select
to authenticated
using (true);



